# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tornado-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tornado
  template:
    metadata:
      labels:
        app: tornado
    spec:
      containers:
      - name: tornado-gke
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/multi-k8s-123123/helloworld-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"